---

- name: install docker module for python 
  pip:
    name: docker

  
- name: start docker 
  service:
    name: docker
    state: started
    enabled: yes

#  - name: starting nginx
#    shell: docker run -d -p 8080:80 nginx

- name: pull and start nginx containar
  docker_container:
    image: nginx:stable
    name: nginx
    auto_remove: true
    state: started
    ports: 
      - "8080:80"