---

- include: ubuntu_install.yml
  when : ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
- include: redhat_install.yml
  when : ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat' or ansible_distribution == 'Amazon'
- include: docker_container.yml