---
- name: Print all available facts on ubuntu
  ansible.builtin.debug:
    var: docker_version ,ansible_user ,OS


- name: install dependency on ubuntu
  apt:
    name: "{{install_defalut_dependency[Os] }}"
    state: latest
    update_cache: yes


- name: add GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present


- name: add docker repository to apt
  apt_repository:
    repo: deb "{{docker_repos[Os] }}" focal stable
    state: present


- name: install docker on ubuntu
  apt:
    name: "{{install_docker_loop[Os] }}"
    state: latest
    update_cache: yes

- name: users | adding docker users (for use without sudo) on ubuntu
  user:
    name: "{{ item }}"
    append: yes
    groups: docker
  become: true
  with_items: "{{docker_users_loop[Os] }}"



