---
- hosts: aws_ec2
  become: true
  tasks:

  - name: install dependency
    apt:
      name: "{{item}}"
      state: latest
      update_cache: yes
    loop:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - python3-pip
  
  - name: add GPG key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present



  - name: add docker repository to apt
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu focal stable
      state: present

  - name: install docker
    apt:
      name: "{{item}}"
      state: latest
      update_cache: yes
    loop:
      - docker-ce
      - docker-ce-cli
      - containerd.io

  - name: install docker module for python
    pip:
      name: docker
  
  
  - name: start docker
    service:
      name: docker
      state: started
      enabled: yes

#  - name: starting nginx
#    shell: docker run -d -p 8080:80 nginx


  - name: pull and start nginx containar
    docker_container:
      image: nginx:stable
      name: nginx
      auto_remove: true
      state: started
      ports: 
        - "8080:80"

  handlers:
  - name: restart docker
    service: 
      name: docker 
      state: restarted