---
- name: run over all ec2 servers
  hosts: aws_ec2
  become: true
  remote_user:  "{{ 'ubuntu' if platform_details == 'Linux/UNIX'  else 'centos' if platform_details == 'CentOs'  else 'ec2-user' }}" 
  
  roles:
  - nginx
  vars: 
     Os: "{{ 'ubuntu' if platform_details == 'Linux/UNIX'  else 'centos' if platform_details == 'CentOs'  else 'ec2-user' }}" 